# Generated by Django 5.1.3 on 2024-11-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
            ],
        ),
    ]
